image: "node:14-alpine"

stages:
    - test
    - quality

before_script:
    - npm ci

include:
    - template: Code-Quality.gitlab-ci.yml

unit_tests:
    stage: test
    script: npm test

linting:
    stage: quality
    script: npm run lint

code_quality:
    stage: quality
    before_script:
        - ''
    rules:
        - if: $CODE_QUALITY_DISABLED
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run code quality job in merge request pipelines
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
        - if: $CI_COMMIT_TAG # Run code quality job in pipelines for tags

code_quality_html:
    extends: code_quality
    stage: quality
    variables:
        REPORT_FORMAT: html
    artifacts:
        paths: [gl-code-quality-report.html]
